name: CI

on:
  pull_request:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Build
        run: pnpm run build

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Types
        run: pnpm run types

      - name: Test
        run: pnpm run test
